INSERT INTO Skills (Skill_Name) VALUES 
('SQL'),
('Data Analysis'),
('Database'),
('Commumication'),
('Data Visualization'),
('Statistics'),
('Programming'),
('ETL'),
('Computer Science'),
('Analytic '),
('Mathematics'),
('Data Mining'),
('Data Science'),
('Statistical Analysis'),
('Big Data'),
('Machine Learning'),
('AI'),
('ecommerce'),
('Business Analytic '),
('Data Engineering'),
('Quanantive Analysis'),
('Data Warehousing'),
('Adobe & Google Analytics'),
('Programming knowledge'),
('Scripting & Statistical skills'),
('Reporting & data visualization'),
('SQL/ database knowledge'),
('Spread-Sheet knowledge'),
('Data Warehousing & ETL'),
('Advanced programming knowledge'),
('Hadoop-based Analytics'),
('In-depth knowledge of SQL/ database'),
('Data architecture & pipelining'),
('Machine learning concept knowledge'),
('Scripting, reporting & data visualization'),
('Statistical & Analytical skills'),
('Machine Learning & Deep learning principles'),
('In-depth programming knowledge (SAS/R/ Python coding)'),
(' Hadoop-based analytics'),
(' Data optimization'),
(' Decision making and soft skills'),
('Data Wrangling'),
('Deep Learning'),
('Python'),
('R')